[[shortcuts]]
name = "<i class='fas fa-home'></i> Home"
identifier = "Home"
#url = "/"
weight = 1

[[shortcuts]]
name = "<i class='fas fa-comments'></i> RIOT channel"
identifier = "RIOT"
url = "https://riot.im/app/#/room/#evlproject:matrix.org/"
weight = 2

[[shortcuts]]
name = "<i class='fas fa-comment-dots'></i> Mailing list"
identifier = "ML"
url = "https://xenomai.org/mailman/listinfo/xenomai/"
weight = 3
